module ReadConfig.Tests where

import           Test.Tasty              (TestTree, testGroup)
import           Test.Tasty.HUnit        (testCase)
import           Test.HUnit              ((@?))

import           ReadConfig
import           Types (Recipe)
import           Paths_herms hiding (getDataDir) -- This module is generated by cabal
import qualified Text.Read as TR

tests :: TestTree
tests = testGroup "UnitConversions"
    [ testCase "testParseConfig" $ do
        path <- getDataFileName "config.hs"
        contents <- readFile path
        (case TR.readEither (dropComments contents) :: Either String ConfigInfo of
          Left  _ -> False
          Right _ -> True) @? "Couldn't parse config file"
    , testCase "testParseRecipes" $ do
        path <- getDataFileName "recipes.herms"
        contents <- readFile path
        (foldl
          (\acc ln ->
             acc && case TR.readEither ln :: Either String Recipe of
                      Left  _ -> False
                      Right _ -> True)
          True
          (lines contents)) @? "Couldn't parse recipes"
    ]
